name: Dependencies Check

on:
  schedule:
    # Запуск каждый понедельник в 9:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      update_dependencies:
        description: 'Update dependencies to latest versions'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '18'

jobs:
  check-dependencies:
    name: Check Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated dependencies
        run: npm outdated || true

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=moderate

      - name: Check for unused dependencies
        run: npx depcheck --ignores="@types/*" || true

      - name: Create dependency report
        run: |
          echo "## Dependency Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Outdated Dependencies:" >> $GITHUB_STEP_SUMMARY
          npm outdated --json 2>/dev/null | jq -r 'to_entries[] | "**\(.key):** \(.value.current) → \(.value.latest)"' >> $GITHUB_STEP_SUMMARY || echo "No outdated dependencies found" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Security Vulnerabilities:" >> $GITHUB_STEP_SUMMARY
          npm audit --json 2>/dev/null | jq -r '.vulnerabilities | to_entries[] | "**\(.key):** \(.value.severity) - \(.value.title)"' >> $GITHUB_STEP_SUMMARY || echo "No security vulnerabilities found" >> $GITHUB_STEP_SUMMARY

  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    if: github.event.inputs.update_dependencies == 'true'
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update dependencies
        run: |
          npm update
          npm audit fix

      - name: Run tests after update
        run: |
          npm test
          npm run lint
          npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            ## Dependency Updates

            This PR updates dependencies to their latest versions.

            ### Changes:
            - Updated npm packages to latest compatible versions
            - Fixed security vulnerabilities
            - All tests passing

            ### Checklist:
            - [x] All tests pass
            - [x] Linting passes
            - [x] Build succeeds
            - [x] No breaking changes detected

            Please review the changes and merge if everything looks good.
          branch: chore/update-dependencies
          delete-branch: true
